INSERT INTO office VALUES(10000, '總公司');
INSERT INTO office VALUES(20000, '分公司');
INSERT INTO department VALUES(11100, '人資部');
INSERT INTO department VALUES(12100, '資訊一部');
INSERT INTO seating_chart(floor_no, seat_no, office_id, state) VALUES(1, 1, 10000, 1);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(1, 2, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(1, 3, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(1, 4, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id, state) VALUES(1, 5, 10000, 1);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(1, 6, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(1, 7, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(1, 8, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(1, 9, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(1, 10, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(2, 1, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(2, 2, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(2, 3, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(2, 4, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(2, 5, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(2, 6, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(2, 7, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(2, 8, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(2, 9, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(2, 10, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id, state) VALUES(3, 1, 10000, 1);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(3, 2, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(3, 3, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(3, 4, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id, state) VALUES(3, 5, 10000, 1);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(3, 6, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(3, 7, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(3, 8, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(3, 9, 10000);
INSERT INTO seating_chart(floor_no, seat_no, office_id) VALUES(3, 10, 10000);
INSERT INTO employee(emp_name, email, dept_id) VALUES('員工A', 'empA@mail.com', 11100);
INSERT INTO employee(emp_name, email, dept_id) VALUES('員工B', 'empB@mail.com', 11100);
INSERT INTO employee(emp_name, email, dept_id) VALUES('員工C', 'empC@mail.com', 11100);
INSERT INTO employee(emp_name, email, dept_id) VALUES('員工D', 'empD@mail.com', 12100);
INSERT INTO employee(emp_name, email, dept_id) VALUES('員工E', 'empE@mail.com', 12100);
INSERT INTO employee(emp_name, email, dept_id) VALUES('員工F', 'empF@mail.com', 12100);
update employee set floor_seat_seq = 1 where emp_name = '員工C';
update employee set floor_seat_seq = 5 where emp_name = '員工D';
update employee set floor_seat_seq = 21 where emp_name = '員工E';
update employee set floor_seat_seq = 25 where emp_name = '員工F';